package org.tempuri.ws_xsd.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * gSOAP 2.8.3 generated service definition
 * 
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * Service service = new Service();
 * ServicePortType portType = service.getService();
 * portType.getParkingInfos(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "Service", targetNamespace = "http://tempuri.org/ws.xsd/Service.wsdl", wsdlLocation = "file:/D:/java/ws.wsdl")
public class Service extends javax.xml.ws.Service {

	private final static URL SERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(org.tempuri.ws_xsd.service.Service.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.tempuri.ws_xsd.service.Service.class.getResource(".");
			url = new URL(baseUrl, "file:/D:/java/ws.wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/java/ws.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SERVICE_WSDL_LOCATION = url;
	}

	public Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public Service() {
		super(SERVICE_WSDL_LOCATION, new QName("http://tempuri.org/ws.xsd/Service.wsdl", "Service"));
	}

	/**
	 * 
	 * @return returns ServicePortType
	 */
	@WebEndpoint(name = "Service")
	public ServicePortType getService() {
		return super.getPort(new QName("http://tempuri.org/ws.xsd/Service.wsdl", "Service"), ServicePortType.class);
	}

}
