
package com.hikvision.cms.ws.server;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-02-24T10:01:06.763+08:00
 * Generated source version: 3.1.10
 * 
 */
public final class ThirdSdkServicePortType_ThirdSdkServiceHttpSoap11Endpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://server.ws.cms.hikvision.com", "thirdSdkService");

    private ThirdSdkServicePortType_ThirdSdkServiceHttpSoap11Endpoint_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ThirdSdkService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ThirdSdkService ss = new ThirdSdkService(wsdlURL, SERVICE_NAME);
        ThirdSdkServicePortType port = ss.getThirdSdkServiceHttpSoap11Endpoint();  
        
        {
        System.out.println("Invoking userLogin...");
        java.lang.String _userLogin_xml = "";
        java.lang.String _userLogin__return = port.userLogin(_userLogin_xml);
        System.out.println("userLogin.result=" + _userLogin__return);


        }
        {
        System.out.println("Invoking getAccessDoorRegionNotNullPage...");
        java.lang.String _getAccessDoorRegionNotNullPage_xml = "";
        java.lang.String _getAccessDoorRegionNotNullPage__return = port.getAccessDoorRegionNotNullPage(_getAccessDoorRegionNotNullPage_xml);
        System.out.println("getAccessDoorRegionNotNullPage.result=" + _getAccessDoorRegionNotNullPage__return);


        }
        {
        System.out.println("Invoking getPMSUrl...");
        java.lang.String _getPMSUrl_xml = "";
        java.lang.String _getPMSUrl__return = port.getPMSUrl(_getPMSUrl_xml);
        System.out.println("getPMSUrl.result=" + _getPMSUrl__return);


        }
        {
        System.out.println("Invoking getAccessControlPage...");
        java.lang.String _getAccessControlPage_xml = "";
        java.lang.String _getAccessControlPage__return = port.getAccessControlPage(_getAccessControlPage_xml);
        System.out.println("getAccessControlPage.result=" + _getAccessControlPage__return);


        }
        {
        System.out.println("Invoking saveOrUpdateOpsThirdDevice...");
        java.lang.String _saveOrUpdateOpsThirdDevice_xml = "";
        java.lang.String _saveOrUpdateOpsThirdDevice__return = port.saveOrUpdateOpsThirdDevice(_saveOrUpdateOpsThirdDevice_xml);
        System.out.println("saveOrUpdateOpsThirdDevice.result=" + _saveOrUpdateOpsThirdDevice__return);


        }
        {
        System.out.println("Invoking getClockRecordPage...");
        java.lang.String _getClockRecordPage_xml = "";
        java.lang.String _getClockRecordPage__return = port.getClockRecordPage(_getClockRecordPage_xml);
        System.out.println("getClockRecordPage.result=" + _getClockRecordPage__return);


        }
        {
        System.out.println("Invoking getAllOpsThirdDevice...");
        java.lang.String _getAllOpsThirdDevice_xml = "";
        java.lang.String _getAllOpsThirdDevice__return = port.getAllOpsThirdDevice(_getAllOpsThirdDevice_xml);
        System.out.println("getAllOpsThirdDevice.result=" + _getAllOpsThirdDevice__return);


        }
        {
        System.out.println("Invoking updateUser...");
        java.lang.String _updateUser_xml = "";
        java.lang.String _updateUser__return = port.updateUser(_updateUser_xml);
        System.out.println("updateUser.result=" + _updateUser__return);


        }
        {
        System.out.println("Invoking getRecordResultPage...");
        java.lang.String _getRecordResultPage_xml = "";
        java.lang.String _getRecordResultPage__return = port.getRecordResultPage(_getRecordResultPage_xml);
        System.out.println("getRecordResultPage.result=" + _getRecordResultPage__return);


        }
        {
        System.out.println("Invoking getProgramPage...");
        java.lang.String _getProgramPage_xml = "";
        java.lang.String _getProgramPage__return = port.getProgramPage(_getProgramPage_xml);
        System.out.println("getProgramPage.result=" + _getProgramPage__return);


        }
        {
        System.out.println("Invoking getAllServer...");
        java.lang.String _getAllServer_xml = "";
        java.lang.String _getAllServer__return = port.getAllServer(_getAllServer_xml);
        System.out.println("getAllServer.result=" + _getAllServer__return);


        }
        {
        System.out.println("Invoking getAllRouteAndPointInfo...");
        java.lang.String _getAllRouteAndPointInfo_xml = "";
        java.lang.String _getAllRouteAndPointInfo__return = port.getAllRouteAndPointInfo(_getAllRouteAndPointInfo_xml);
        System.out.println("getAllRouteAndPointInfo.result=" + _getAllRouteAndPointInfo__return);


        }
        {
        System.out.println("Invoking filterControlUnitId...");
        java.util.List<java.lang.Integer> _filterControlUnitId_controlUnitIds = null;
        java.lang.Integer _filterControlUnitId_userId = null;
        java.util.List<java.lang.Integer> _filterControlUnitId__return = port.filterControlUnitId(_filterControlUnitId_controlUnitIds, _filterControlUnitId_userId);
        System.out.println("filterControlUnitId.result=" + _filterControlUnitId__return);


        }
        {
        System.out.println("Invoking getPrivilegeResult...");
        java.lang.String _getPrivilegeResult_xml = "";
        java.lang.String _getPrivilegeResult__return = port.getPrivilegeResult(_getPrivilegeResult_xml);
        System.out.println("getPrivilegeResult.result=" + _getPrivilegeResult__return);


        }
        {
        System.out.println("Invoking getAccessControlByUserNamePage...");
        java.lang.String _getAccessControlByUserNamePage_xml = "";
        java.lang.String _getAccessControlByUserNamePage__return = port.getAccessControlByUserNamePage(_getAccessControlByUserNamePage_xml);
        System.out.println("getAccessControlByUserNamePage.result=" + _getAccessControlByUserNamePage__return);


        }
        {
        System.out.println("Invoking getGateInfo...");
        java.lang.String _getGateInfo_xml = "";
        java.lang.String _getGateInfo__return = port.getGateInfo(_getGateInfo_xml);
        System.out.println("getGateInfo.result=" + _getGateInfo__return);


        }
        {
        System.out.println("Invoking getPresons...");
        java.lang.String _getPresons_xml = "";
        java.lang.String _getPresons__return = port.getPresons(_getPresons_xml);
        System.out.println("getPresons.result=" + _getPresons__return);


        }
        {
        System.out.println("Invoking getCardsPageResult...");
        java.lang.String _getCardsPageResult_xml = "";
        java.lang.String _getCardsPageResult__return = port.getCardsPageResult(_getCardsPageResult_xml);
        System.out.println("getCardsPageResult.result=" + _getCardsPageResult__return);


        }
        {
        System.out.println("Invoking getEncoderInfo...");
        java.lang.String _getEncoderInfo_xml = "";
        java.lang.String _getEncoderInfo__return = port.getEncoderInfo(_getEncoderInfo_xml);
        System.out.println("getEncoderInfo.result=" + _getEncoderInfo__return);


        }
        {
        System.out.println("Invoking getDeviceStatus...");
        java.lang.String _getDeviceStatus_xml = "";
        java.lang.String _getDeviceStatus__return = port.getDeviceStatus(_getDeviceStatus_xml);
        System.out.println("getDeviceStatus.result=" + _getDeviceStatus__return);


        }
        {
        System.out.println("Invoking getAlarmChannel...");
        java.lang.String _getAlarmChannel_xml = "";
        java.lang.String _getAlarmChannel__return = port.getAlarmChannel(_getAlarmChannel_xml);
        System.out.println("getAlarmChannel.result=" + _getAlarmChannel__return);


        }
        {
        System.out.println("Invoking getPassCarsCounting...");
        java.lang.String _getPassCarsCounting_xml = "";
        java.lang.String _getPassCarsCounting__return = port.getPassCarsCounting(_getPassCarsCounting_xml);
        System.out.println("getPassCarsCounting.result=" + _getPassCarsCounting__return);


        }
        {
        System.out.println("Invoking getAlarmEventPage...");
        java.lang.String _getAlarmEventPage_xml = "";
        java.lang.String _getAlarmEventPage__return = port.getAlarmEventPage(_getAlarmEventPage_xml);
        System.out.println("getAlarmEventPage.result=" + _getAlarmEventPage__return);


        }
        {
        System.out.println("Invoking getIoPage...");
        java.lang.String _getIoPage_xml = "";
        java.lang.String _getIoPage__return = port.getIoPage(_getIoPage_xml);
        System.out.println("getIoPage.result=" + _getIoPage__return);


        }
        {
        System.out.println("Invoking getPersonAndCards...");
        java.lang.String _getPersonAndCards_xml = "";
        java.lang.String _getPersonAndCards__return = port.getPersonAndCards(_getPersonAndCards_xml);
        System.out.println("getPersonAndCards.result=" + _getPersonAndCards__return);


        }
        {
        System.out.println("Invoking importPersonAndCardInfo...");
        java.lang.String _importPersonAndCardInfo_xml = "";
        java.lang.String _importPersonAndCardInfo__return = port.importPersonAndCardInfo(_importPersonAndCardInfo_xml);
        System.out.println("importPersonAndCardInfo.result=" + _importPersonAndCardInfo__return);


        }
        {
        System.out.println("Invoking getDepartments...");
        java.lang.String _getDepartments_xml = "";
        java.lang.String _getDepartments__return = port.getDepartments(_getDepartments_xml);
        System.out.println("getDepartments.result=" + _getDepartments__return);


        }
        {
        System.out.println("Invoking getAccessDoorPage...");
        java.lang.String _getAccessDoorPage_xml = "";
        java.lang.String _getAccessDoorPage__return = port.getAccessDoorPage(_getAccessDoorPage_xml);
        System.out.println("getAccessDoorPage.result=" + _getAccessDoorPage__return);


        }
        {
        System.out.println("Invoking deleteUser...");
        java.lang.String _deleteUser_xml = "";
        java.lang.String _deleteUser__return = port.deleteUser(_deleteUser_xml);
        System.out.println("deleteUser.result=" + _deleteUser__return);


        }
        {
        System.out.println("Invoking userLogOut...");
        java.lang.String _userLogOut_xml = "";
        java.lang.String _userLogOut__return = port.userLogOut(_userLogOut_xml);
        System.out.println("userLogOut.result=" + _userLogOut__return);


        }
        {
        System.out.println("Invoking getControlUnitInfo...");
        java.lang.String _getControlUnitInfo_xml = "";
        java.lang.String _getControlUnitInfo__return = port.getControlUnitInfo(_getControlUnitInfo_xml);
        System.out.println("getControlUnitInfo.result=" + _getControlUnitInfo__return);


        }
        {
        System.out.println("Invoking getCameraInfo...");
        java.lang.String _getCameraInfo_xml = "";
        java.lang.String _getCameraInfo__return = port.getCameraInfo(_getCameraInfo_xml);
        System.out.println("getCameraInfo.result=" + _getCameraInfo__return);


        }
        {
        System.out.println("Invoking getRoutePage...");
        java.lang.String _getRoutePage_xml = "";
        java.lang.String _getRoutePage__return = port.getRoutePage(_getRoutePage_xml);
        System.out.println("getRoutePage.result=" + _getRoutePage__return);


        }
        {
        System.out.println("Invoking getAllPersonInspectionResult...");
        java.lang.String _getAllPersonInspectionResult_xml = "";
        java.lang.String _getAllPersonInspectionResult__return = port.getAllPersonInspectionResult(_getAllPersonInspectionResult_xml);
        System.out.println("getAllPersonInspectionResult.result=" + _getAllPersonInspectionResult__return);


        }
        {
        System.out.println("Invoking userOnlineHearbeat...");
        java.lang.String _userOnlineHearbeat_xml = "";
        java.lang.String _userOnlineHearbeat__return = port.userOnlineHearbeat(_userOnlineHearbeat_xml);
        System.out.println("userOnlineHearbeat.result=" + _userOnlineHearbeat__return);


        }
        {
        System.out.println("Invoking getSchedulingHistoryPage...");
        java.lang.String _getSchedulingHistoryPage_xml = "";
        java.lang.String _getSchedulingHistoryPage__return = port.getSchedulingHistoryPage(_getSchedulingHistoryPage_xml);
        System.out.println("getSchedulingHistoryPage.result=" + _getSchedulingHistoryPage__return);


        }
        {
        System.out.println("Invoking getPassCarsInfo...");
        java.lang.String _getPassCarsInfo_xml = "";
        java.lang.String _getPassCarsInfo__return = port.getPassCarsInfo(_getPassCarsInfo_xml);
        System.out.println("getPassCarsInfo.result=" + _getPassCarsInfo__return);


        }
        {
        System.out.println("Invoking getPTZSeizeTime...");
        java.lang.String _getPTZSeizeTime_xml = "";
        java.lang.String _getPTZSeizeTime__return = port.getPTZSeizeTime(_getPTZSeizeTime_xml);
        System.out.println("getPTZSeizeTime.result=" + _getPTZSeizeTime__return);


        }
        {
        System.out.println("Invoking getParkingInfo...");
        java.lang.String _getParkingInfo_xml = "";
        java.lang.String _getParkingInfo__return = port.getParkingInfo(_getParkingInfo_xml);
        System.out.println("getParkingInfo.result=" + _getParkingInfo__return);


        }
        {
        System.out.println("Invoking getEcsControlPage...");
        java.lang.String _getEcsControlPage_xml = "";
        java.lang.String _getEcsControlPage__return = port.getEcsControlPage(_getEcsControlPage_xml);
        System.out.println("getEcsControlPage.result=" + _getEcsControlPage__return);


        }
        {
        System.out.println("Invoking getParkingRegions...");
        java.lang.String _getParkingRegions_xml = "";
        java.lang.String _getParkingRegions__return = port.getParkingRegions(_getParkingRegions_xml);
        System.out.println("getParkingRegions.result=" + _getParkingRegions__return);


        }
        {
        System.out.println("Invoking covertListToString...");
        java.util.List<java.lang.String> _covertListToString_list = null;
        java.lang.String _covertListToString__return = port.covertListToString(_covertListToString_list);
        System.out.println("covertListToString.result=" + _covertListToString__return);


        }
        {
        System.out.println("Invoking getAccessEventPage...");
        java.lang.String _getAccessEventPage_xml = "";
        java.lang.String _getAccessEventPage__return = port.getAccessEventPage(_getAccessEventPage_xml);
        System.out.println("getAccessEventPage.result=" + _getAccessEventPage__return);


        }
        {
        System.out.println("Invoking doControl...");
        java.lang.String _doControl_xml = "";
        java.lang.String _doControl__return = port.doControl(_doControl_xml);
        System.out.println("doControl.result=" + _doControl__return);


        }
        {
        System.out.println("Invoking getAllAlarmState...");
        java.lang.String _getAllAlarmState_xml = "";
        java.lang.String _getAllAlarmState__return = port.getAllAlarmState(_getAllAlarmState_xml);
        System.out.println("getAllAlarmState.result=" + _getAllAlarmState__return);


        }
        {
        System.out.println("Invoking getCameraPreviewUrl...");
        java.lang.String _getCameraPreviewUrl_xml = "";
        java.lang.String _getCameraPreviewUrl__return = port.getCameraPreviewUrl(_getCameraPreviewUrl_xml);
        System.out.println("getCameraPreviewUrl.result=" + _getCameraPreviewUrl__return);


        }
        {
        System.out.println("Invoking addUser...");
        java.lang.String _addUser_xml = "";
        java.lang.String _addUser__return = port.addUser(_addUser_xml);
        System.out.println("addUser.result=" + _addUser__return);


        }
        {
        System.out.println("Invoking deleteOpsThirdDeviceBySysCode...");
        java.lang.String _deleteOpsThirdDeviceBySysCode_xml = "";
        java.lang.String _deleteOpsThirdDeviceBySysCode__return = port.deleteOpsThirdDeviceBySysCode(_deleteOpsThirdDeviceBySysCode_xml);
        System.out.println("deleteOpsThirdDeviceBySysCode.result=" + _deleteOpsThirdDeviceBySysCode__return);


        }
        {
        System.out.println("Invoking getAlarmDeviceInfo...");
        java.lang.String _getAlarmDeviceInfo_xml = "";
        java.lang.String _getAlarmDeviceInfo__return = port.getAlarmDeviceInfo(_getAlarmDeviceInfo_xml);
        System.out.println("getAlarmDeviceInfo.result=" + _getAlarmDeviceInfo__return);


        }
        {
        System.out.println("Invoking getSchedulingPage...");
        java.lang.String _getSchedulingPage_xml = "";
        java.lang.String _getSchedulingPage__return = port.getSchedulingPage(_getSchedulingPage_xml);
        System.out.println("getSchedulingPage.result=" + _getSchedulingPage__return);


        }

        System.exit(0);
    }

}
