
package com.hikvision.cms.ws.server;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-02-24T10:01:06.803+08:00
 * Generated source version: 3.1.10
 * 
 */
 
public class ThirdSdkServicePortType_ThirdSdkServiceHttpSoap11Endpoint_Server{

    protected ThirdSdkServicePortType_ThirdSdkServiceHttpSoap11Endpoint_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ThirdSdkServiceHttpSoap11EndpointImpl();
        String address = "http://10.123.115.67/services/thirdSdkService.thirdSdkServiceHttpSoap11Endpoint/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ThirdSdkServicePortType_ThirdSdkServiceHttpSoap11Endpoint_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
