package com.hikvision.cms.ws.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-02-24T10:01:06.805+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "thirdSdkService", 
                  wsdlLocation = "http://10.123.115.67/services/thirdSdkService?wsdl",
                  targetNamespace = "http://server.ws.cms.hikvision.com") 
public class ThirdSdkService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.ws.cms.hikvision.com", "thirdSdkService");
    public final static QName ThirdSdkServiceHttpSoap12Endpoint = new QName("http://server.ws.cms.hikvision.com", "thirdSdkServiceHttpSoap12Endpoint");
    public final static QName ThirdSdkServiceHttpSoap11Endpoint = new QName("http://server.ws.cms.hikvision.com", "thirdSdkServiceHttpSoap11Endpoint");
    static {
        URL url = null;
        try {
            url = new URL("http://10.123.115.67/services/thirdSdkService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ThirdSdkService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.123.115.67/services/thirdSdkService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ThirdSdkService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ThirdSdkService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ThirdSdkService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ThirdSdkService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ThirdSdkService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ThirdSdkService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ThirdSdkServicePortType
     */
    @WebEndpoint(name = "thirdSdkServiceHttpSoap12Endpoint")
    public ThirdSdkServicePortType getThirdSdkServiceHttpSoap12Endpoint() {
        return super.getPort(ThirdSdkServiceHttpSoap12Endpoint, ThirdSdkServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ThirdSdkServicePortType
     */
    @WebEndpoint(name = "thirdSdkServiceHttpSoap12Endpoint")
    public ThirdSdkServicePortType getThirdSdkServiceHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(ThirdSdkServiceHttpSoap12Endpoint, ThirdSdkServicePortType.class, features);
    }


    /**
     *
     * @return
     *     returns ThirdSdkServicePortType
     */
    @WebEndpoint(name = "thirdSdkServiceHttpSoap11Endpoint")
    public ThirdSdkServicePortType getThirdSdkServiceHttpSoap11Endpoint() {
        return super.getPort(ThirdSdkServiceHttpSoap11Endpoint, ThirdSdkServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ThirdSdkServicePortType
     */
    @WebEndpoint(name = "thirdSdkServiceHttpSoap11Endpoint")
    public ThirdSdkServicePortType getThirdSdkServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(ThirdSdkServiceHttpSoap11Endpoint, ThirdSdkServicePortType.class, features);
    }

}
